version: '3.8'

services:

  web:
    container_name: django-web
    build:
      context: ./app  # Path to the directory containing Dockerfile
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app  # Ensure this matches your local directory structure
    env_file:
      - ./.env.dev  # Ensure your environment file is correctly referenced
    ports:
      - "8000:8000"
    depends_on:
      - db
