version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306

  web:
    container_name: django-web
    build:
      context: ./app  # Adjust to point to the directory containing Dockerfile
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app  # Ensure this matches your local directory structure
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
