version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env

  web:
    container_name: django-web
    build:
      context: ./app  # Path to the directory containing Dockerfile
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app  # Ensure this matches your local directory structure
    env_file:
      - ./.env.dev  # Ensure your environment file is correctly referenced
    ports:
      - "8000:8000"
    depends_on:
      - db
